include:
 - ./common/monitoring/docker-compose.yaml
 - ./common/minio/docker-compose.yaml
 - ./common/vault/docker-compose.yaml
 - ./common/uptime/docker-compose.yaml
#  - ./common/clickhouse/docker-compose.yaml
 - ./common/redis/docker-compose.yaml
 - ./common/db/docker-compose.yaml
#  - ./common/registry/docker-compose.yaml
 - ./common/rabbitmq/docker-compose.yaml
 - ./common/kong/docker-compose.yaml
#  - ./common/pgweb/docker-compose.yaml
 - ./common/hasura/docker-compose.yaml
 - ./common/keycloak/docker-compose.yaml
 - ./cofounder-match/docker-compose.yaml
#  - ./user-management-service/docker-compose.yaml


services:
  caddy:
    extends:
      file: common/caddy/docker-compose.yaml
      service: caddy
    volumes:
     - ./cofounder-match:/etc/caddy/cofounder-match
     - ./user-management-service:/etc/user-management-service

volumes:
  caddy_data:
  caddy_config:
