services:
  hasura_ai:
    image: hasura/graphql-engine:v2.46.0
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL_AI_SERVICE:?HASURA_GRAPHQL_DATABASE_URL_AI_SERVICE is not set}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE:-true} # Enabled to true for console view for CLI to be done to false 
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET_AI_SERVICE:?HASURA_GRAPHQL_ADMIN_SECRET_AI_SERVICE is not set}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE:-public}