services:
  cofounder_match_backend:
      image: ghcr.io/${org}/cofounder-match-backend:${COFOUNDER_MATCH_BACKEND_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        DATABASE_URL: ${BACKEND_DATABASE_URL:?BACKEND_DATABASE_URL is not set}
        MINIO_BUCKET_NAME: ${BACKEND_MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is not set}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?MINIO_BUCKET_NAME is not set}
        MINIO_URL: ${MINIO_URL:?MINIO_URL is not set}
        GUPSHUP_WHATSAPP_API_URL: ${GUPSHUP_WHATSAPP_API_URL:?GUPSHUP_WHATSAPP_API_URL is not set}
        GUPSHUP_API_KEY: ${GUPSHUP_API_KEY:?GUPSHUP_API_KEY is not set}
        GUPSHUP_SOURCE_NUMBER: ${GUPSHUP_SOURCE_NUMBER:?GUPSHUP_SOURCE_NUMBER is not set}
        GUPSHUP_APP_ID: ${GUPSHUP_APP_ID:?GUPSHUP_APP_ID is not set}
        GUPSHUP_WHATSAPP_TEMPLATE_ID: ${GUPSHUP_WHATSAPP_TEMPLATE_ID:?GUPSHUP_WHATSAPP_TEMPLATE_ID is not set}
        GUPSHUP_SRC_NAME: ${GUPSHUP_SRC_NAME:?GUPSHUP_SRC_NAME is not set}
        GUPSHUP_SMS_API_URL: ${GUPSHUP_SMS_API_URL:?GUPSHUP_SMS_API_URL is not set}
        GUPSHUP_SMS_USER_ID: ${GUPSHUP_SMS_USER_ID:?GUPSHUP_SMS_USER_ID is not set}
        GUPSHUP_SMS_PASSWORD: ${GUPSHUP_SMS_PASSWORD:?GUPSHUP_SMS_PASSWORD is not set}
