services:
  cofounder_match_backend:
      image: ghcr.io/${org}/cofounder-match-backend:${COFOUNDER_MATCH_BACKEND_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        DATABASE_URL: ${BACKEND_DATABASE_URL:?BACKEND_DATABASE_URL is not set}
        MINIO_BUCKET_NAME: ${BACKEND_MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is not set}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?MINIO_BUCKET_NAME is not set}
        # MINIO_ENDPOINT: ${MINIO_ENDPOINT:?MINIO_ENDPOINT is not set}
        MINIO_URL: ${MINIO_URL:?MINIO_URL is not set}