services:
  cofounder_match_app:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Cofounder-Match/app.git#${APP_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        NEXT_PUBLIC_GOOGLE_API_KEY: ${NEXT_PUBLIC_GOOGLE_API_KEY:?NEXT_PUBLIC_GOOGLE_API_KEY is not set}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:?NEXT_PUBLIC_BACKEND_URL is not set}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY:?NEXT_PUBLIC_FIREBASE_API_KEY is not set}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:?NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN is not set}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID:?NEXT_PUBLIC_FIREBASE_PROJECT_ID is not set}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:?NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET is not set}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:?NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID is not set}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID:?NEXT_PUBLIC_FIREBASE_APP_ID is not set}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:?NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID is not set}
        NEXT_PUBLIC_OPENAI_API_KEY: ${NEXT_PUBLIC_OPENAI_API_KEY:?NEXT_PUBLIC_OPENAI_API_KEY is not set}
        NEXT_PUBLIC_LINKEDIN_CLIENT_ID: ${NEXT_PUBLIC_LINKEDIN_CLIENT_ID:?NEXT_PUBLIC_LINKEDIN_CLIENT_ID is not set}
        NEXT_PUBLIC_LINKEDIN_REDIRECT_URI: ${NEXT_PUBLIC_LINKEDIN_REDIRECT_URI:?NEXT_PUBLIC_LINKEDIN_REDIRECT_URI is not set}
        NEXT_PUBLIC_LINKEDIN_CLIENT_SECRET: ${NEXT_PUBLIC_LINKEDIN_CLIENT_SECRET:?NEXT_PUBLIC_LINKEDIN_CLIENT_SECRET is not set}
