services:
  cofounder_match_app:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Cofounder-Match/app.git#${APP_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        NEXT_PUBLIC_GOOGLE_API_KEY: ${NEXT_PUBLIC_GOOGLE_API_KEY:?NEXT_PUBLIC_GOOGLE_API_KEY is not set}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:?NEXT_PUBLIC_BACKEND_URL is not set}